package com.jwt.hibernate.bean;
// Generated 18-May-2017 12:52:35 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Long id;
	private String type;
	
	private boolean createRole;
	private boolean readRole;
	private boolean updateRole;
	private boolean deleteRole;

	
	private boolean createUser;
	private boolean readUser;
	private boolean updateUser;
	private boolean deleteUser;

	private boolean createClient;
	private boolean readClient;
	private boolean updateClient;
	private boolean deleteClient;


	private boolean createAppointment;
	private boolean readAppointment;
	private boolean updateAppointment;
	private boolean deleteAppointment;

	private boolean createTreatment;
	private boolean readTreatment;
	private boolean updateTreatment;
	private boolean deleteTreatment;

	
	public Role() {
	}
	public Role(String type){
		this.type = type;
		this.createRole = false;
		this.readRole = false;
		this.updateRole = false;
		this.deleteRole = false;
		
		this.createUser = false;
		this.readUser = false;
		this.updateUser = false;
		this.deleteUser = false;
		
		this.createClient = false;
		this.readClient = false;
		this.updateClient = false;
		this.deleteClient = false;

		this.createAppointment = false;
		this.readAppointment = false;
		this.updateAppointment = false;
		this.deleteAppointment = false;

		this.createTreatment = false;
		this.readTreatment = false;
		this.updateTreatment = false;
		this.deleteTreatment = false;

	}
	
	

 	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	public boolean isCreateRole() {
		return createRole;
	}
	public void setCreateRole(boolean createRole) {
		this.createRole = createRole;
	}
	public boolean isReadRole() {
		return readRole;
	}
	public void setReadRole(boolean readRole) {
		this.readRole = readRole;
	}
	public boolean isUpdateRole() {
		return updateRole;
	}
	public void setUpdateRole(boolean updateRole) {
		this.updateRole = updateRole;
	}
	public boolean isDeleteRole() {
		return deleteRole;
	}
	public void setDeleteRole(boolean deleteRole) {
		this.deleteRole = deleteRole;
	}
	public boolean isReadUser() {
		return readUser;
	}
	public void setReadUser(boolean readUser) {
		this.readUser = readUser;
	}
	public boolean isCreateUser() {
		return createUser;
	}
	public void setCreateUser(boolean createUser) {
		this.createUser = createUser;
	}
	public boolean isUpdateUser() {
		return updateUser;
	}
	public void setUpdateUser(boolean updateUser) {
		this.updateUser = updateUser;
	}
	public boolean isDeleteUser() {
		return deleteUser;
	}
	public void setDeleteUser(boolean deleteUser) {
		this.deleteUser = deleteUser;
	}
	public boolean isCreateClient() {
		return createClient;
	}
	public void setCreateClient(boolean createClient) {
		this.createClient = createClient;
	}
	public boolean isReadClient() {
		return readClient;
	}
	public void setReadClient(boolean readClient) {
		this.readClient = readClient;
	}
	public boolean isUpdateClient() {
		return updateClient;
	}
	public void setUpdateClient(boolean updateClient) {
		this.updateClient = updateClient;
	}
	public boolean isDeleteClient() {
		return deleteClient;
	}
	public void setDeleteClient(boolean deleteClient) {
		this.deleteClient = deleteClient;
	}
	public boolean isCreateAppointment() {
		return createAppointment;
	}
	public void setCreateAppointment(boolean createAppointment) {
		this.createAppointment = createAppointment;
	}
	public boolean isReadAppointment() {
		return readAppointment;
	}
	public void setReadAppointment(boolean readAppointment) {
		this.readAppointment = readAppointment;
	}
	public boolean isUpdateAppointment() {
		return updateAppointment;
	}
	public void setUpdateAppointment(boolean updateAppointment) {
		this.updateAppointment = updateAppointment;
	}
	public boolean isDeleteAppointment() {
		return deleteAppointment;
	}
	public void setDeleteAppointment(boolean deleteAppointment) {
		this.deleteAppointment = deleteAppointment;
	}
	public boolean isCreateTreatment() {
		return createTreatment;
	}
	public void setCreateTreatment(boolean createTreatment) {
		this.createTreatment = createTreatment;
	}
	public boolean isReadTreatment() {
		return readTreatment;
	}
	public void setReadTreatment(boolean readTreatment) {
		this.readTreatment = readTreatment;
	}
	public boolean isUpdateTreatment() {
		return updateTreatment;
	}
	public void setUpdateTreatment(boolean updateTreatment) {
		this.updateTreatment = updateTreatment;
	}
	public boolean isDeleteTreatment() {
		return deleteTreatment;
	}
	public void setDeleteTreatment(boolean deleteTreatment) {
		this.deleteTreatment = deleteTreatment;
	}
}
