package com.jwt.hibernate.bean;
// Generated 18-May-2017 12:52:35 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Long id;
	private String type;
	
	private String roles;
	private String clients;
	private String users;
	private String appointments;
	private String treatments;
	

	public Role() {
	}
	public Role(String type){
		this.type = type;
		this.roles = "";
		this.clients = "";
		this.appointments = "";
		this.treatments = "";
		this.users = "";
	
	}
	
	

 	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	public String getUsers(){
		return this.users;
	}
	public void setUsers(String u){
		this.users = u;
	}
	public String getClients(){
		return this.clients;
	}
	public void setClients (String c){
		this.clients = c;
	}
	public String getAppointments(){
		return this.appointments;
	}
	public void setAppointments (String a){
		this.appointments = a;
	}
	public String getTreatments(){
		return this.treatments;
	}
	public void setTreatments (String t){
		this.treatments = t;
	}
	public String getRoles(){
		return this.roles;
	}
	public void setRoles (String r){
		this.roles = r;
	}
	
	
	public boolean isCreateRole() {
		return this.roles.contains("C");
	}
	public boolean isReadRole() {
		return this.roles.contains("R");
	}
	public boolean isUpdateRole() {
		return this.roles.contains("U");
	}
	public boolean isDeleteRole() {
		return this.roles.contains("D");
	}
	
	public boolean isCreateUser() {
		return this.users.contains("C");
	}
	public boolean isReadUser() {
		return this.users.contains("R");
	}
	public boolean isUpdateUser() {
		return this.users.contains("U");
	}
	public boolean isDeleteUser() {
		return this.users.contains("D");
	}
	
	public boolean isCreateClient() {
		return this.clients.contains("C");
	}
	public boolean isReadClient() {
		return this.clients.contains("R");
	}
	public boolean isUpdateClient() {
		return this.clients.contains("U");
	}
	public boolean isDeleteClient() {
		return this.clients.contains("D");
	}
	
	public boolean isCreateAppointment() {
		return this.appointments.contains("C");
	}
	public boolean isReadAppointment() {
		return this.appointments.contains("R");
	}
	public boolean isUpdateAppointment() {
		return this.appointments.contains("U");
	}
	public boolean isDeleteAppointment() {
		return this.appointments.contains("D");
	}
	
	public boolean isCreateTreatment() {
		return this.treatments.contains("C");
	}
	public boolean isReadTreatment() {
		return this.treatments.contains("R");
	}
	public boolean isUpdateTreatment() {
		return this.treatments.contains("U");
	}
	public boolean isDeleteTreatment() {
		return this.treatments.contains("D");
	}
}
