package com.jwt.hibernate.bean;


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.hibernate.Session;
import org.hibernate.Transaction;

import com.jwt.hibernate.dao.HibernateUtil;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Long id;
	private boolean valid;
	private String login;
	private String password;
	private String name;
	private String surname;
	private String pesel;
	private String phone;
	private String city;
	private String address;
	private String userName;
	private String email;
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<Appointment> appointments = new HashSet<Appointment>(0);	
	private String activeRoleString = null;

	public User() {
		this.valid = false;
	}
	
	public User(String login, String password){
		this.login = login;
		this.password = password;
		this.activeRoleString = null;
	}

	public User(String login, String password, String name, String surname, String pesel) {
		this.login = login;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.pesel = pesel;
		this.activeRoleString = null;
	}

	public User(String login, String password, String name, String surname, String pesel, String phone, String city,
			String address, String userName, String email, Set<Role> roles, Set appointments, String activeRoleId) {
		this.login = login;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.pesel = pesel;
		this.phone = phone;
		this.city = city;
		this.address = address;
		this.userName = userName;
		this.email = email;
		this.roles = roles;
		this.appointments = appointments;
		this.activeRoleString = activeRoleId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public boolean isValid(){
		return this.valid;
	}
	public void setValid(boolean valid){
		this.valid = valid;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getPesel() {
		return this.pesel;
	}

	public void setPesel(String pesel) {
		this.pesel = pesel;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	public Set getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set appointments) {
		this.appointments = appointments;
	}

	public String getActiveRoleString() {
		return this.activeRoleString;
	}

	public void setActiveRoleString(String activeRoleId) {
		this.activeRoleString = activeRoleId;
	}

/*	public Set<Role> getRolesList(){
		Set<Role> ret = new HashSet<Role>(0);
		List<Long> list = new ArrayList<Long>(0);
		List<Role> roleList = new ArrayList<Role>(0);
		Session session = HibernateUtil.getSessionFactory().openSession();	
		Transaction trns = session.beginTransaction();            
		String hql = "FROM User_Role WHERE user_id = '" + this.id + "'";
		list = session.createQuery(hql).list();		
		
		for (Role role : list){
			hql = "FROM Role WHERE id = '" + _id + "'";
			roleList = session.createQuery(hql).list();
			ret.add(roleList.get(0));
		}
		
		return ret;
	}*/
}

